"""Session-first CRUD operations for __APP_NAME__."""

from __future__ import annotations

from sqlalchemy import func, select
from sqlalchemy.orm import Session, joinedload

# BEGIN AUTOGENERATED IMPORTS
from src.services.__APP_SLUG__.core.utils import generate_resource_id
from src.services.__APP_SLUG__.database.schema import Principal, Resource
# END AUTOGENERATED IMPORTS


# BEGIN SHARED HELPERS
def get_principal_by_id(session: Session, principal_id: str) -> Principal | None:
    return session.get(Principal, principal_id)


def get_principal_id_by_email(session: Session, email: str) -> str | None:
    row = (
        session.execute(select(Principal.id).where(Principal.email == email))
        .scalars()
        .first()
    )
    return row
# END SHARED HELPERS


# BEGIN ENDPOINT IMPLEMENTATIONS
def list_resources(
    session: Session,
    *,
    principal_id: str,
    offset: int = 0,
    limit: int = 100,
) -> tuple[list[Resource], int]:
    base_filter = (Resource.principal_id == principal_id, Resource.deleted.is_(False))

    total_count = session.execute(
        select(func.count(Resource.id)).where(*base_filter)
    ).scalar_one()

    entries = (
        session.execute(
            select(Resource)
            .where(*base_filter)
            .order_by(Resource.created_at.desc(), Resource.id.asc())
            .offset(offset)
            .limit(limit)
            .options(joinedload(Resource.principal))
        )
        .scalars()
        .all()
    )
    return entries, int(total_count)


def get_resource_by_id(session: Session, resource_id: str) -> Resource | None:
    return (
        session.execute(
            select(Resource)
            .where(Resource.id == resource_id, Resource.deleted.is_(False))
            .options(joinedload(Resource.principal))
        )
        .scalars()
        .first()
    )


def create_resource(
    session: Session,
    *,
    principal_id: str,
    name: str,
    payload: dict | None = None,
) -> Resource:
    record = Resource(
        id=generate_resource_id(),
        principal_id=principal_id,
        name=name,
        payload=payload,
        deleted=False,
    )
    session.add(record)
    session.flush()
    session.refresh(record)
    return get_resource_by_id(session, record.id) or record


def update_resource(
    session: Session,
    *,
    resource_id: str,
    name: str | None = None,
    payload: dict | None = None,
) -> Resource | None:
    record = session.get(Resource, resource_id)
    if record is None or record.deleted:
        return None

    if name is not None:
        record.name = name
    if payload is not None:
        record.payload = payload

    session.flush()
    session.refresh(record)
    return get_resource_by_id(session, record.id) or record


def delete_resource(session: Session, *, resource_id: str) -> bool:
    record = session.get(Resource, resource_id)
    if record is None or record.deleted:
        return False

    record.deleted = True
    session.flush()
    return True
# END ENDPOINT IMPLEMENTATIONS

