"""ORM schema template for __APP_NAME__."""

from __future__ import annotations

from typing import Any

from sqlalchemy import Boolean, ForeignKey, Index, String, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

# BEGIN AUTOGENERATED IMPORTS
from src.services.__APP_SLUG__.database.base import Base, TimestampMixin
# END AUTOGENERATED IMPORTS


# BEGIN RESOURCE DECLARATIONS
class Principal(Base, TimestampMixin):
    """Acting user/account identity used by request impersonation."""

    __tablename__ = "__APP_SLUG___principals"

    id: Mapped[str] = mapped_column(String(255), primary_key=True)
    email: Mapped[str] = mapped_column(String(320), unique=True, nullable=False)
    display_name: Mapped[str | None] = mapped_column(String(255))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true")

    resources: Mapped[list["Resource"]] = relationship(
        back_populates="principal",
        cascade="all,delete-orphan",
    )


class Resource(Base, TimestampMixin):
    """Canonical example entity for scaffolded REST CRUD endpoints."""

    __tablename__ = "__APP_SLUG___resources"
    __table_args__ = (
        UniqueConstraint("principal_id", "name", name="uq___APP_SLUG___resource_name"),
        Index("ix___APP_SLUG___resource_principal", "principal_id"),
    )

    id: Mapped[str] = mapped_column(String(255), primary_key=True)
    principal_id: Mapped[str] = mapped_column(
        ForeignKey("__APP_SLUG___principals.id"),
        nullable=False,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    payload: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    deleted: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")

    principal: Mapped[Principal] = relationship(back_populates="resources")
# END RESOURCE DECLARATIONS

