"""Serialization helpers for __APP_NAME__ REST API."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

# BEGIN AUTOGENERATED IMPORTS
from src.services.__APP_SLUG__.database.schema import Principal, Resource
# END AUTOGENERATED IMPORTS


# BEGIN SHARED HELPERS
def _to_camel_case(snake_str: str) -> str:
    parts = snake_str.split("_")
    return parts[0] + "".join(part.title() for part in parts[1:])


def _format_datetime(value: datetime | None) -> str | None:
    if value is None:
        return None
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.isoformat()


def _clean_dict(data: dict[str, Any], *, exclude_none: bool = True) -> dict[str, Any]:
    cleaned: dict[str, Any] = {}
    for key, value in data.items():
        if exclude_none and value is None:
            continue
        cleaned[_to_camel_case(key)] = value
    return cleaned
# END SHARED HELPERS


# BEGIN ENDPOINT IMPLEMENTATIONS
def serialize_principal_mini(principal: Principal) -> dict[str, Any]:
    return {
        "id": principal.id,
        "email": principal.email,
        "displayName": principal.display_name,
    }


def serialize_resource(resource: Resource) -> dict[str, Any]:
    payload = {
        "id": resource.id,
        "name": resource.name,
        "payload": resource.payload,
        "owner": serialize_principal_mini(resource.principal),
        "created_at": _format_datetime(resource.created_at),
        "updated_at": _format_datetime(resource.updated_at),
    }
    return _clean_dict(payload)


def serialize_resource_list(
    entries: list[Resource],
    *,
    total_count: int,
    offset: int,
    limit: int,
) -> dict[str, Any]:
    return {
        "totalCount": total_count,
        "offset": offset,
        "limit": limit,
        "entries": [serialize_resource(entry) for entry in entries],
    }
# END ENDPOINT IMPLEMENTATIONS

