"""
__APP_NAME__ REST API routes.

Template notes:
- Mounted under /api/env/{env_id}/services/__SERVICE_MOUNT_NAME__
- DB session comes from request.state.db_session (IsolationMiddleware)
- User impersonation comes from request.state.impersonate_user_id / impersonate_email
"""

from __future__ import annotations

from typing import Any

from starlette import status
from starlette.requests import Request
from starlette.responses import JSONResponse
from starlette.routing import Route
from sqlalchemy.orm import Session

# BEGIN AUTOGENERATED IMPORTS
from src.services.__APP_SLUG__.core.errors import (
    AppAPIError,
    bad_request,
    handle_exception,
    not_found,
    unauthorized,
)
from src.services.__APP_SLUG__.core.serializers import (
    serialize_resource,
    serialize_resource_list,
)
from src.services.__APP_SLUG__.core.utils import parse_int_param
from src.services.__APP_SLUG__.database import operations as ops
# END AUTOGENERATED IMPORTS


# BEGIN SHARED HELPERS
def _session(request: Request) -> Session:
    """Get the environment-scoped DB session from request.state."""
    session = getattr(request.state, "db_session", None)
    if session is None:
        raise unauthorized("Missing database session")
    return session


def _principal_user_id(request: Request) -> str:
    """Resolve the acting principal from request state."""
    principal = getattr(request.state, "impersonate_user_id", None)
    if principal is not None and str(principal).strip() != "":
        return str(principal)

    # For MVP template we keep email-based fallback as a scaffold hook.
    principal_email = getattr(request.state, "impersonate_email", None)
    if principal_email:
        resolved = ops.get_principal_id_by_email(_session(request), principal_email)
        if resolved is not None:
            return resolved

    raise unauthorized("Missing user authentication")


async def _parse_json_body(request: Request) -> dict[str, Any]:
    """Parse JSON body and raise app-shaped bad_request on malformed input."""
    try:
        return await request.json()
    except Exception as exc:  # pylint: disable=broad-except
        raise bad_request(f"Invalid JSON body: {exc}") from exc
# END SHARED HELPERS


# BEGIN ENDPOINT IMPLEMENTATIONS
async def list_resources(request: Request) -> JSONResponse:
    """GET /resources"""
    try:
        session = _session(request)
        principal_id = _principal_user_id(request)
        offset = parse_int_param(request.query_params.get("offset"), default=0, minimum=0)
        limit = parse_int_param(request.query_params.get("limit"), default=100, minimum=1)
        entries, total_count = ops.list_resources(
            session=session,
            principal_id=principal_id,
            offset=offset,
            limit=limit,
        )
        payload = serialize_resource_list(entries, total_count=total_count, offset=offset, limit=limit)
        return JSONResponse(payload, status_code=status.HTTP_200_OK)
    except AppAPIError as exc:
        return exc.to_response()
    except Exception as exc:  # pylint: disable=broad-except
        return handle_exception(exc)


async def get_resource_by_id(request: Request) -> JSONResponse:
    """GET /resources/{resource_id}"""
    try:
        session = _session(request)
        resource_id = request.path_params["resource_id"]
        record = ops.get_resource_by_id(session=session, resource_id=resource_id)
        if record is None:
            raise not_found("Resource not found")
        return JSONResponse(serialize_resource(record), status_code=status.HTTP_200_OK)
    except AppAPIError as exc:
        return exc.to_response()
    except Exception as exc:  # pylint: disable=broad-except
        return handle_exception(exc)


async def create_resource(request: Request) -> JSONResponse:
    """POST /resources"""
    try:
        session = _session(request)
        principal_id = _principal_user_id(request)
        body = await _parse_json_body(request)

        name = body.get("name")
        if not isinstance(name, str) or not name.strip():
            raise bad_request("Field 'name' is required")

        payload = body.get("payload")
        record = ops.create_resource(
            session=session,
            principal_id=principal_id,
            name=name.strip(),
            payload=payload,
        )
        return JSONResponse(serialize_resource(record), status_code=status.HTTP_201_CREATED)
    except AppAPIError as exc:
        return exc.to_response()
    except Exception as exc:  # pylint: disable=broad-except
        return handle_exception(exc)


async def patch_resource_by_id(request: Request) -> JSONResponse:
    """PATCH /resources/{resource_id}"""
    try:
        session = _session(request)
        resource_id = request.path_params["resource_id"]
        body = await _parse_json_body(request)

        record = ops.update_resource(
            session=session,
            resource_id=resource_id,
            name=body.get("name"),
            payload=body.get("payload"),
        )
        if record is None:
            raise not_found("Resource not found")

        return JSONResponse(serialize_resource(record), status_code=status.HTTP_200_OK)
    except AppAPIError as exc:
        return exc.to_response()
    except Exception as exc:  # pylint: disable=broad-except
        return handle_exception(exc)


async def delete_resource_by_id(request: Request) -> JSONResponse:
    """DELETE /resources/{resource_id}"""
    try:
        session = _session(request)
        resource_id = request.path_params["resource_id"]
        deleted = ops.delete_resource(session=session, resource_id=resource_id)
        if not deleted:
            raise not_found("Resource not found")
        return JSONResponse({}, status_code=status.HTTP_204_NO_CONTENT)
    except AppAPIError as exc:
        return exc.to_response()
    except Exception as exc:  # pylint: disable=broad-except
        return handle_exception(exc)
# END ENDPOINT IMPLEMENTATIONS


# BEGIN RESOURCE DECLARATIONS
routes = [
    Route("/resources", list_resources, methods=["GET"]),
    Route("/resources", create_resource, methods=["POST"]),
    Route("/resources/{resource_id}", get_resource_by_id, methods=["GET"]),
    Route("/resources/{resource_id}", patch_resource_by_id, methods=["PATCH"]),
    Route("/resources/{resource_id}", delete_resource_by_id, methods=["DELETE"]),
]
# END RESOURCE DECLARATIONS

