app_slug: asana
app_name: Asana
openapi_path: inputs/openapi.scoped.json
target_dir: ../../../backend/src/services/asana
resources:
  tasks:
    aliases:
    - dependencies
    - dependency
    - dependent
    - dependents
    - duplicate_of
    - duplicated_from
    - parent
    - target
    - task
    - tasks
    - task_base
    - task_compact
    - task_request
    - task_response
    primary_key: gid
    self_id_fields:
    - gid
  projects:
    aliases:
    - project
    - projects
    - project_base
    - project_compact
    - project_request
    - project_response
    - project_update_request
    primary_key: gid
    self_id_fields:
    - gid
  sections:
    aliases:
    - new_section
    - old_section
    - section
    - sections
    - section_base
    - section_compact
    - section_response
    primary_key: gid
    self_id_fields:
    - gid
  tags:
    aliases:
    - tag
    - tags
    - tag_base
    - tag_base_request
    - tag_compact
    - tag_create_request
    - tag_create_tag_for_workspace_request
    - tag_response
    - tag_update_request
    primary_key: gid
    self_id_fields:
    - gid
  users:
    aliases:
    - assigned_by
    - assignee
    - completed_by
    - created_by
    - follower
    - followers
    - owner
    - user
    - users
    - user_base
    - user_base_response
    - user_compact
    - user_response
    primary_key: gid
    self_id_fields:
    - gid
  teams:
    aliases:
    - team
    - teams
    - team_base
    - team_compact
    - team_request
    - team_response
    primary_key: gid
    self_id_fields:
    - gid
  workspaces:
    aliases:
    - workspace
    - workspaces
    - workspace_base
    - workspace_compact
    - workspace_request
    - workspace_response
    primary_key: gid
    self_id_fields:
    - gid
  stories:
    aliases:
    - stories
    - story
    - story_base
    - story_compact
    - story_request
    - story_response
    primary_key: gid
    self_id_fields:
    - gid
naming:
  qualifier_prefixes:
  - parent_
  - source_
  - target_
  pk_field_names:
  - gid
  self_id_fields:
  - gid
